// Code generated by restgen. DO NOT EDIT.

package types

import (
	"time"
)

type Contact struct {
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	Email     *string    `json:"email,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

type ContactList struct {
	Items []Contact `json:"items"`
	Total int       `json:"total"`
}

type DeleteResult struct {
	Success bool `json:"success"`
}

type Location struct {
	Iso2      string `json:"iso2"`
	StateCode string `json:"stateCode"`
	Name      string `json:"name"`
}

type LocationList struct {
	Items []Location `json:"items"`
	Total int        `json:"total"`
}

type CreateContactInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UpdateContactInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type ContactFilter struct {
	Search *string `json:"search,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

type LocationUpdate struct {
	Name   string `json:"name"`
	Active *bool  `json:"active,omitempty"`
}

type LocationQuery struct {
	Search  *string `json:"search,omitempty"`
	Country *string `json:"country,omitempty"`
	Limit   *int    `json:"limit,omitempty"`
	Offset  *int    `json:"offset,omitempty"`
}
