// Code generated by restgen. DO NOT EDIT ABOVE THE MARKER.

package routes

import (
	models "example/types"
	"net/http"

	"github.com/borderlesshq/restgen/shared"
	"github.com/go-chi/chi/v5"
)

// ============================================================================
// HANDLER
// ============================================================================

type ContactsHandler struct {
	// add dependencies here
}

type ContactsParam func(*ContactsHandler)

func NewContactsHandler(params ...ContactsParam) *ContactsHandler {
	h := &ContactsHandler{}
	for _, param := range params {
		param(h)
	}
	shared.AssertDependencies(*h, "NewContactsHandler")
	return h
}

// ============================================================================
// ROUTES
// ============================================================================

func (h *ContactsHandler) BasePath() string {
	return "/v1/contacts"
}

func (h *ContactsHandler) Routes() chi.Router {
	r := chi.NewRouter()
	h.applyMiddleware(r)
	r.Post("/", h.CreateContact)
	r.Get("/{id}", h.GetContact)
	r.Put("/{id}", h.UpdateContact)
	r.Delete("/{id}", h.DeleteContact)
	r.Get("/", h.ListContacts)
	r.Put("/locations/{iso2}/states/{stateCode}", h.UpdateLocation)
	r.Get("/locations/search", h.SearchLocations)

	return r
}

// ============================================================================
// MIDDLEWARE (add your middleware here)
// ============================================================================

func (h *ContactsHandler) applyMiddleware(r chi.Router) {
	// Example:
	// r.Use(middleware.RequestID)
	// r.Use(middleware.Logger)
	//
	// Per-route middleware can be applied in Routes() using r.With(...)
}

// RouteMiddleware returns middleware for specific routes.
// This is for documentation/introspection; apply via r.With() in Routes().
func (h *ContactsHandler) RouteMiddleware() map[string][]func(http.Handler) http.Handler {
	return map[string][]func(http.Handler) http.Handler{
		// "POST /": {rateLimiter},
		// "GET /{id}": {cacheMiddleware},
	}
}

// --- RESTGEN MARKER (do not edit above) ---

// ============================================================================
// HANDLER IMPLEMENTATIONS
// ============================================================================

func (h *ContactsHandler) CreateContact(w http.ResponseWriter, r *http.Request) {
	// var input models.CreateContactInput
	// if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
	//     shared.WriteResponse(w, http.StatusBadRequest, &shared.ApiResponse[*models.Contact]{
	//         Message: err.Error(),
	//     })
	//     return
	// }

	// TODO: implement CreateContact
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.Contact]{
		Message: "CreateContact not implemented",
	})
}

func (h *ContactsHandler) GetContact(w http.ResponseWriter, r *http.Request) {
	// Path parameters:
	// id := chi.URLParam(r, "id")

	// TODO: implement GetContact
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.Contact]{
		Message: "GetContact not implemented",
	})
}

func (h *ContactsHandler) UpdateContact(w http.ResponseWriter, r *http.Request) {
	// Path parameters:
	// id := chi.URLParam(r, "id")
	// var input models.UpdateContactInput
	// if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
	//     shared.WriteResponse(w, http.StatusBadRequest, &shared.ApiResponse[*models.Contact]{
	//         Message: err.Error(),
	//     })
	//     return
	// }

	// TODO: implement UpdateContact
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.Contact]{
		Message: "UpdateContact not implemented",
	})
}

func (h *ContactsHandler) DeleteContact(w http.ResponseWriter, r *http.Request) {
	// Path parameters:
	// id := chi.URLParam(r, "id")

	// TODO: implement DeleteContact
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.DeleteResult]{
		Message: "DeleteContact not implemented",
	})
}

func (h *ContactsHandler) ListContacts(w http.ResponseWriter, r *http.Request) {
	// Query parameters:
	// var filter models.ContactFilter
	// decoder := schema.NewDecoder()
	// decoder.IgnoreUnknownKeys(true)
	// if err := decoder.Decode(&filter, r.URL.Query()); err != nil {
	//     shared.WriteResponse(w, http.StatusBadRequest, &shared.ApiResponse[*models.ContactList]{
	//         Message: err.Error(),
	//     })
	//     return
	// }

	// TODO: implement ListContacts
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.ContactList]{
		Message: "ListContacts not implemented",
	})
}

func (h *ContactsHandler) UpdateLocation(w http.ResponseWriter, r *http.Request) {
	// Path parameters:
	// iso2 := chi.URLParam(r, "iso2")
	// stateCode := chi.URLParam(r, "stateCode")
	// var location models.LocationUpdate
	// if err := json.NewDecoder(r.Body).Decode(&location); err != nil {
	//     shared.WriteResponse(w, http.StatusBadRequest, &shared.ApiResponse[*models.Location]{
	//         Message: err.Error(),
	//     })
	//     return
	// }

	// TODO: implement UpdateLocation
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.Location]{
		Message: "UpdateLocation not implemented",
	})
}

func (h *ContactsHandler) SearchLocations(w http.ResponseWriter, r *http.Request) {
	// Query parameters:
	// var query models.LocationQuery
	// decoder := schema.NewDecoder()
	// decoder.IgnoreUnknownKeys(true)
	// if err := decoder.Decode(&query, r.URL.Query()); err != nil {
	//     shared.WriteResponse(w, http.StatusBadRequest, &shared.ApiResponse[*models.LocationList]{
	//         Message: err.Error(),
	//     })
	//     return
	// }

	// TODO: implement SearchLocations
	shared.WriteResponse(w, http.StatusNotImplemented, &shared.ApiResponse[*models.LocationList]{
		Message: "SearchLocations not implemented",
	})
}

// --- REMOVED HANDLERS ---
